name: capcards
description: "an application for memorization through spaced repetition."
publish_to: 'none' 

version: 1.3.0+4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2
  package_info_plus: ^5.0.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"  # Para Android
  ios: false  # Mude para true se quiser iOS tambÃ©m
  image_path: "assets/images/logo.png"  # Caminho da sua imagem

flutter:

  uses-material-design: true
  assets:
    - assets/icon/icon.png

